title: 'SQLFlow'
description: Bridging Data and AI
repository: sql-machine-learning/sql-machine-learning.github.io

permalink: pretty
exclude: ['*.sql', '*.go', '.gitignore', '*.sh', '*.proto', '*.y', '*.py', 'vendor', 'gohive/doc/design.md', 'gohive/docker/README.md', 'pysqlflow/doc/design/client_design_doc.md', 'pysqlflow/doc/design/magic_design_doc.md', 'sqlflow/doc/mysql-setup.md', 'sqlflow/doc/tutorial/aspara2019/', 'sqlflow/python/README.md', 'sqlflow/parser/README.md', 'sqlflow/parser/remote/README.md', 'sqlflow/parser/remote/hiveql/README.md', 'sqlflow/scripts/markdown_link_check/README.md', 'sqlflow/pkg/sql/codegen/xgboost/README.md', 'sqlflow/doc/model_parameter.md', 'sqlflow/doc/argo-setup.md', 'sqlflow/doc/design/ant_xgboost.md', 'sqlflow/doc/design/codegen_couler_use_ir.md', 'sqlflow/doc/design/couler_sqlflow.md', 'sqlflow/doc/design/high_available_sqlflow_server.md', 'sqlflow/doc/design/model_zoo_pai.md', 'sqlflow/java/parser/README.md', 'sqlflow/pkg/sql/tpp/README.md', 'sqlflow/python/couler/README.md', 'sqlflow/doc/design/workflow.md', 'sqlflow/scripts/tensorflow_step_image/README.md', 'sqlflow/pkg/parser/external/README.md', 'sqlflow/doc/tutorial/apsara2019/README.md', 'goalisa/README.md', 'sqlflow/doc/contribute_models.md', 'sqlflow/doc/run/workflow_mode.md', 'playground/sqlflow', 'playground/index.html', 'playground/README.md']

search_enabled: true
search_tokenizer_separator: /[\s/]+/

heading_anchors: true

aux_links:
  "GitHub":
    - "https://github.com/sql-machine-learning/sqlflow"


remote_theme: pmarsceill/just-the-docs
classes: wide
color_scheme: nil
ga_tracking: UA-17331483-8

defaults:
  - scope:
      path: "sqlflow_getstarted"
    values:
      layout: "doc"
      nav_exclude: false
      grand_parent: Get Started
      prefix: '/sqlflow/'
  - scope:
      path: "sqlflow_installation"
    values:
      layout: "doc"
      nav_exclude: false
      grand_parent: Installation
      prefix: '/sqlflow/'
  - scope:
      path: "sqlflow_examples"
    values:
      layout: "doc"
      nav_exclude: false
      grand_parent: Examples
      prefix: '/sqlflow/'
  - scope:
      path: "sqlflow_design"
    values:
      layout: "doc"
      nav_exclude: false
      grand_parent: Design
      prefix: '/sqlflow/'
  - scope:
      path: "sqlflow_contributes"
    values:
      layout: "doc"
      nav_exclude: false
      grand_parent: Contributes
      prefix: '/sqlflow/'
  - scope:
      path: "models"
    values:
      layout: "doc"
      nav_exclude: true
      grand_parent: Models 
  - scope:
      path: "elasticdl"
    values:
      layout: "doc"
      nav_exclude: true
      grand_parent: ElasticDL 
      prefix: '/elasticdl/'
  - scope:
      path: "sqlflow/doc/quick_start.md"
    values:
      nav_exclude: false
      parent: Get Started
      nav_order: 1
  - scope:
      path: "sqlflow/doc/language_guide.md"
    values:
      nav_exclude: false 
      parent: Get Started
      nav_order: 2
  - scope:
      path: "sqlflow/doc/run/repl.md"
    values:
      nav_exclude: true
      parent: Get Started
      nav_order: 3
  - scope:
      path: "playground/dev.md"
    values:
      nav_exclude: false
      parent: Get Started
      grand_parent: Installation
      nav_order: 4
  - scope:
      path: "sqlflow/doc/run/docker.md"
    values:
      nav_exclude: false
      parent: Installation
      nav_order: 1
  - scope:
      path: "sqlflow/doc/run/gcp.md"
    values:
      nav_exclude: false
      parent: Install SQLFlow on Cloud
      grand_parent: Installation
      nav_order: 1
  - scope:
      path: "sqlflow/doc/run/kubernetes.md"
    values:
      nav_exclude: false
      parent: Install SQLFlow on Cloud
      grand_parent: Installation
      nav_order: 2
  - scope:
      path: "sqlflow/doc/run_with_mysql.md"
    values:
      nav_exclude: false
      parent: Run SQLFlow with SQL Engines
      grand_parent: Installation
      nav_order: 1
  - scope:
      path: "sqlflow/doc/run_with_hive.md"
    values:
      nav_exclude: false
      parent: Run SQLFlow with SQL Engines
      grand_parent: Installation
      nav_order: 2
  - scope:
      path: "sqlflow/doc/run_with_maxcompute.md"
    values:
      nav_exclude: false
      parent: Run SQLFlow with SQL Engines
      grand_parent: Installation
      nav_order: 3
  - scope:
      path: "sqlflow/doc/tutorial/iris-dnn.md"
    values:
      nav_exclude: false
      parent: Examples
      nav_order: 1
  - scope:
      path: "sqlflow/doc/tutorial/imdb-stackedbilstm.md"
    values:
      nav_exclude: false
      parent: Examples
      nav_order: 2
  - scope:
      path: "sqlflow/doc/tutorial/fraud-dnn.md"
    values:
      nav_exclude: false
      parent: Examples
      nav_order: 4
  - scope:
      path: "sqlflow/doc/tutorial/housing-xgboost.md"
    values:
      nav_exclude: false
      parent: Examples
      nav_order: 5
  - scope:
      path: "sqlflow/doc/tutorial/housing-explain.md"
    values:
      nav_exclude: false
      parent: Examples
      nav_order: 6
  - scope:
      path: "sqlflow/doc/tutorial/energe_lstmbasedtimeseries.md"
    values:
      nav_exclude: false
      parent: Examples
      nav_order: 7
  - scope:
      path: "sqlflow/doc/tutorial/apsara2019/carprice_xgboost/README.md"
    values:
      nav_exclude: false
      parent: Examples
      nav_order: 8
  - scope:
      path: "sqlflow/doc/tutorial/apsara2019/titanic_dnn/README.md"
    values:
      nav_exclude: false
      parent: Examples
      nav_order: 9
  - scope:
      path: "sqlflow/doc/tutorial/apsara2019/carprice_xgboost/README.md"
    values:
      nav_exclude: false
      parent: Examples
      nav_order: 10
  - scope:
      path: "sqlflow/doc/tutorial/apsara2019/activepower_clustering/README.md"
    values:
      nav_exclude: false
      parent: Examples
      nav_order: 11
  - scope:
      path: "sqlflow/doc/design/syntax.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 1
  - scope:
      path: "sqlflow/doc/design/sqlflow_parser.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 2
  - scope:
      path: "sqlflow/doc/design/pipe.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 3
  - scope:
      path: "sqlflow/doc/design/intermediate_representation.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 4
  - scope:
      path: "sqlflow/doc/design/database_abstraction_layer.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 5
  - scope:
      path: "sqlflow/doc/design/submitter.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 2
  - scope:
      path: "sqlflow/doc/design/alps_submitter.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 6
  - scope:
      path: "sqlflow/doc/design/explainer.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 7
  - scope:
      path: "sqlflow/doc/design/xgboost_on_sqlflow.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 8
  - scope:
      path: "sqlflow/doc/design/auth.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 9
  - scope:
      path: "sqlflow/doc/design/clustermodel.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 10
  - scope:
      path: "sqlflow/doc/design/customized_model.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 11
  - scope:
      path: "sqlflow/doc/design/elasticdl_on_sqlflow.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 12
  - scope:
      path: "sqlflow/doc/design/training_and_validation.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 13
  - scope:
      path: "sqlflow/doc/design/train_parameters.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 14
  - scope:
      path: "sqlflow/doc/design/feature_derivation.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 16
  - scope:
      path: "sqlflow/doc/design/close_producer_from_consumer.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 17
  - scope:
      path: "sqlflow/doc/design/high_available_sqlflow_server.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 18
  - scope:
      path: "sqlflow/doc/design/model_zoo.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 19
  - scope:
      path: "sqlflow/doc/design/workflow_package.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 20
  - scope:
      path: "sqlflow/doc/design/sql_program_dependency_analyze.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 21
  - scope:
      path: "sqlflow/doc/design/show_train_stmt.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 22
  - scope:
      path: "sqlflow/doc/design/model_market.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 23
  - scope:
      path: "sqlflow/doc/design/logs.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 24
  - scope:
      path: "sqlflow/doc/design/katib_on_sqlflow.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 25
  - scope:
      path: "sqlflow/doc/design/argo_workflow_on_sqlflow.md"
    values:
      nav_exclude: false
      parent: Design
      nav_order: 26
  - scope:
      path: "sqlflow/doc/build.md"
    values:
      nav_exclude: false
      parent: Contributes
      nav_order: 1
  - scope:
      path: "sqlflow/doc/walkthrough.md"
    values:
      nav_exclude: false
      parent: Contributes
      nav_order: 2
  - scope:
      path: "models/doc/contribute_models.md"
    values:
      nav_exclude: false
      parent: Contributes
      grand_parent: SQLFlow
      nav_order: 3
  - scope:
      path: "elasticdl/docs/tutorials/elasticdl_local.md"
    values:
      nav_exclude: false
      parent: ElasticDL
      nav_order: 1
  - scope:
      path: "elasticdl/docs/tutorials/elasticdl_cloud.md"
    values:
      nav_exclude: false
      parent: ElasticDL
      nav_order: 2
  - scope:
      path: "elasticdl/docs/tutorials/elasticdl_on_prem_cluster.md"
    values:
      nav_exclude: false
      parent: ElasticDL
      nav_order: 3
  - scope:
      path: "elasticdl/docs/tutorials/model_contribution.md"
    values:
      nav_exclude: false
      parent: ElasticDL
      nav_order: 4
  - scope:
      path: "elasticdl/docs/tutorials/preprocessing_tutorial.md"
    values:
      nav_exclude: false
      parent: ElasticDL
      nav_order: 5
  - scope:
      path: "elasticdl/docs/tutorials/dev.md"
    values:
      nav_exclude: false
      parent: ElasticDL
      nav_order: 6
  - scope:
      path: "elasticdl/docs/designs/overall.md"
    values:
      nav_exclude: false
      parent: ElasticDL
      nav_order: 7
  - scope:
      path: "elasticdl/docs/designs/high_performance_ps.md"
    values:
      nav_exclude: false
      parent: ElasticDL
      nav_order: 8
  - scope:
      path: "elasticdl/docs/designs/allreduce.md"
    values:
      nav_exclude: false
      parent: ElasticDL
      nav_order: 9
  - scope:
      path: "elasticdl/docs/designs/distributed_embedding_layer.md"
    values:
      nav_exclude: false
      parent: ElasticDL
      nav_order: 10
  - scope:
      path: "elasticdl/docs/designs/dynamic_data_sharding.md"
    values:
      nav_exclude: false
      parent: ElasticDL
      nav_order: 11
  - scope:
      path: "elasticdl/docs/designs/data_io_pipeline.md"
    values:
      nav_exclude: false
      parent: ElasticDL
      nav_order: 12
  - scope:
      path: "elasticdl/docs/designs/custom_data_source_support.md"
    values:
      nav_exclude: false
      parent: ElasticDL
      nav_order: 13
  - scope:
      path: "elasticdl/docs/designs/data_transform.md"
    values:
      nav_exclude: false
      parent: ElasticDL
      nav_order: 14
  - scope:
      path: "elasticdl/docs/designs/model_serving.md"
    values:
      nav_exclude: false
      parent: ElasticDL
      nav_order: 15

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sql-machine-learning"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

relative_links:
  enabled:     true
  collections: true

