remote_theme: pmarsceill/just-the-docs

classes: wide

search_enabled: true

title: 'SQLFlow'

ga_tracking: UA-17331483-8

aux_links:
  "GitHub":
    - "https://github.com/sql-machine-learning/sqlflow"

exclude: ['*.sql', '*.go', '.gitignore', '*.sh', '*.proto', '*.y']

# baseurl: "/sql-machine-learning.github.io/"

defaults:
  - scope:
      path: "pysqlflow"
    values:
        layout: doc
        parent: Pysqlflow
  - scope:
      path: "sqlflow"
    values:
      layout: "doc"
      nav_exclude: true
      prefix: '/sqlflow/'
      grand_parent: Documents
  - scope:
      path: "sqlflow/doc/installation.md"
    values:
      nav_exclude: false
      parent: Documents
      nav_order: 1
  - scope:
      path: "sqlflow/doc/syntax.md"
    values:
      nav_exclude: false
      parent: Design
  - scope:
      path: "sqlflow/doc/walkthrough.md"
    values:
      nav_exclude: false
      parent: Design
  - scope:
      path: "sqlflow/doc/sql_parser.md"
    values:
      nav_exclude: false
      parent: Design
  - scope:
      path: "sqlflow/doc/database_abstraction_layer.md"
    values:
      nav_exclude: false
      parent: Design
  - scope:
      path: "sqlflow/doc/pipe.md"
    values:
      nav_exclude: false
      parent: Design
  - scope:
      path: "sqlflow/doc/build.md"
    values:
      nav_exclude: false
      parent: Contribute
  - scope:
      path: "sqlflow/doc/build-tensorflow.md"
    values:
      nav_exclude: false
      parent: Contribute
  - scope:
      path: "sqlflow/doc/mysql-setup.md"
    values:
      nav_exclude: false
      parent: Contribute
  - scope:
      path: "sqlflow/doc/close_producer_from_consumer.md"
    values:
      nav_exclude: false
      parent: Contribute
  - scope:
      path: "sqlflow/doc/submitter.md"
    values:
      nav_exclude: false
      parent: Contribute


footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sql-machine-learning"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
