remote_theme: pmarsceill/just-the-docs

classes: wide

search_enabled: true

title: 'SQLFLOW'

destination: 'docs'

ga_tracking: UA-17331483-8

aux_links:
  "GitHub":
    - "https://github.com/sql-machine-learning/sqlflow"

exclude: ['*.sql', '*.go', '.gitignore', '*.sh', '*.proto', '*.y']

# baseurl: "/sql-machine-learning.github.io/"

defaults:
  - scope:
      path: "sqlflow"
    values:
      layout: "doc"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sql-machine-learning"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
